### ISSUE TITLE
carouselの表示周りのバグ

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/rackle#74]
- [x] carouselが１個目なのに左にならない時がある。
 - [x] carouselの外をクリックしたらカルーセル閉じたい。
    - carousel出してるとき地図はさわれなくてもいいかもしれない
 - [x] Carouselの画像が連動してない。

**Comment by yamato3310** [comment]
日曜の夜までに完成させます

**Comment by fumihumi** [comment]
close refs #91
